# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_HOST: db
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
